将一个长序列分成batch并截断
![ptb](image/ptb.jpg)

文件夹下的 `reader.py` 来源于 `tensorflow.models.rnn.ptb`

In [1]:
import tensorflow as tf
import reader

#### 1. 读取数据并打印长度及前100位数据。

In [2]:
DATA_PATH = "../datasets/PTB_data"
train_data, valid_data, test_data, _ = reader.ptb_raw_data(DATA_PATH)
print(len(train_data))
print(train_data[:100])

887521
[9969, 9970, 9971, 9973, 9974, 9975, 9979, 9980, 9981, 9982, 9983, 9985, 9986, 9987, 9988, 9990, 9991, 9992, 9993, 9994, 9995, 9996, 9997, 9998, 9255, 1, 2, 71, 392, 32, 2132, 0, 145, 18, 5, 9206, 275, 406, 2, 22, 1, 12, 140, 3, 1, 5464, 0, 3080, 1595, 95, 7681, 1, 2, 71, 392, 7, 336, 140, 3, 2476, 656, 2169, 954, 23, 520, 5, 9206, 275, 3, 38, 302, 437, 3683, 5, 941, 3, 3149, 495, 262, 4, 137, 6091, 4240, 6035, 29, 987, 5, 240, 759, 3, 1014, 2785, 210, 5, 95, 3, 430, 4114, 4, 13]


#### 2. 将训练数据组织成batch大小为4、截断长度为5的数据组。并使用队列读取前3个batch。

In [3]:
# ptb_producer返回的为一个二维的tuple数据。
result = reader.ptb_producer(train_data, 4, 5)

# 通过队列依次读取batch。
with tf.Session() as sess:
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(sess=sess, coord=coord)
    for i in range(3):
        x, y = sess.run(result)
        print("X%d: "%i, x)
        print("Y%d: "%i, y)
    coord.request_stop()
    coord.join(threads)

X0:  [[9969 9970 9971 9973 9974]
 [  38  373    0  653   45]
 [  25   62  488  169 2234]
 [   3  405 1341    3   48]]
Y0:  [[9970 9971 9973 9974 9975]
 [ 373    0  653   45 4661]
 [  62  488  169 2234  374]
 [ 405 1341    3   48   71]]
X1:  [[9975 9979 9980 9981 9982]
 [4661  160    4 1153    0]
 [ 374    1    6   38  306]
 [  71    3 3605    6 9195]]
Y1:  [[9979 9980 9981 9982 9983]
 [ 160    4 1153    0  960]
 [   1    6   38  306   41]
 [   3 3605    6 9195    1]]
X2:  [[9983 9985 9986 9987 9988]
 [ 960    6    0 8594   18]
 [  41   24    4 1145  206]
 [   1    7 9418  220   18]]
Y2:  [[9985 9986 9987 9988 9990]
 [   6    0 8594   18 1830]
 [  24    4 1145  206 2841]
 [   7 9418  220   18    5]]
