### 3.4.5 完整神经网络样例程序
示例：神经网络解决二分类问题

In [1]:
import tensorflow as tf
from numpy.random import RandomState

#### 1. 定义神经网络的参数，输入和输出节点
在shape的一个维度上使用None可以方便使用不大的batch大小。在训练时需要把数据分成比较小的batch，但是在测试时，可以一次性使用全部数据。当数据集比较小时，这样方便测试，但数据集比较大时，将大量数据放入一个batch可能会导致内存溢出。

In [2]:
batch_size = 8
dataset_size = 128
w1= tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1), trainable=True)
w2= tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1), trainable=True)
x = tf.placeholder(tf.float32, shape=(None, 2), name="x-input")
y_= tf.placeholder(tf.float32, shape=(None, 1), name='y-input')

#### 2. 定义前向传播过程，损失函数及反向传播算法

In [3]:
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

# 定义损失函数和反向传播算法
cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0))) 
train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

####  3. 生成模拟数据集。
定义规则来给出样本的标签。这里所有 x1+x2 < 1 的样本都被认为是正样本。1表示正样本，0表示负样本。

In [4]:
rdm = RandomState(1)
X = rdm.rand(dataset_size, 2)
Y = [[int(x1+x2 < 1)] for (x1, x2) in X]

#### 4. 创建一个会话来运行TensorFlow程序。

In [5]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    
    # 输出目前（未经训练）的参数取值。
    print("w1:", sess.run(w1))
    print("w2:", sess.run(w2))
    print("\n")
    
    # 训练模型。
    STEPS = 10000
    for i in range(STEPS):
        # 每次选取batch_size个样本进行训练
        start = (i*batch_size) % dataset_size
        end = (i*batch_size) % dataset_size + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        # 每隔一段时间计算在所有数据上的交叉熵并输出
        if i % 1000 == 0:
            total_cross_entropy = sess.run(cross_entropy, feed_dict={x: X, y_: Y})
            print("After %d training step(s), cross entropy on all data is %g" % (i, total_cross_entropy))
            # 输出训练后的参数取值
            print("w1:", sess.run(w1))
            print("w2:", sess.run(w2))    


w1: [[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
w2: [[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]


After 0 training step(s), cross entropy on all data is 0.0674925
w1: [[-0.8123182   1.4855988   0.06632921]
 [-2.4437041   0.1002484   0.59222424]]
w2: [[-0.8123182 ]
 [ 1.4855988 ]
 [ 0.06632937]]
After 1000 training step(s), cross entropy on all data is 0.0163385
w1: [[-1.2754936  1.9323932  0.7181832]
 [-2.827644   0.4706616  1.1418985]]
w2: [[-1.2119861]
 [ 1.9595636]
 [ 0.5508197]]
After 2000 training step(s), cross entropy on all data is 0.00907547
w1: [[-1.5139761  2.1591146  1.0742906]
 [-3.0170891  0.6484542  1.46365  ]]
w2: [[-1.405064  ]
 [ 2.2063437 ]
 [ 0.83948904]]
After 3000 training step(s), cross entropy on all data is 0.00714436
w1: [[-1.6539441  2.292184   1.2743924]
 [-3.1415606  0.7646775  1.6682037]]
w2: [[-1.5261347]
 [ 2.3539424]
 [ 1.019857 ]]
After 4000 training step(s), cross entropy on all data is 0.00578471
w1: [[-1.7914352 